### ISSUE TITLE
Documentar las funciones de comando

### ISSUE THREAD

**Issue by IvanitiX** [IvanitiX/ArcadiaChatbotPythonEdition#2]
Los comandos que pueden usarse en el bot son bastante variados.
Quizás sería de utilidad explicar qué hace cada comando  por tener un estándar de documentación para próximos commits.

Podría seguirse una estructura del estilo:
```python
"""
Nombre función: ¿Qué hace?
¿Necesita argumentos? De ser así:
- (Argumento): Para qué sirve (Obligatorio/Opcional)
"""
@command
def comando():
    #...
```

**Comment by Alux6** [comment]
¿Podría trabajar en esta issue?

**Comment by IvanitiX** [comment]
Adelante

**Comment by IvanitiX** [comment]
Issue tratada en el PR #4 , ¡Cierro issue!
